NEVNAPOK = {
    1: {  # Január
        1: ["Alpár", "Fruzsina", "Bazil"],
        2: ["Ábel", "Gergely", "Vazul"],
        3: ["Genovéva", "Gyöngyvér", "Benjámin", "Dzsenifer", "Jennifer"],
        4: ["Titusz", "Leona", "Angéla"],
        5: ["Simon", "Emília"],
        6: ["Gáspár", "Menyhért", "Boldizsár"],
        7: ["Attila", "Etele", "Ramóna", "Rajmund", "Bálint"],
        8: ["Gyöngyvér", "Keve", "Szeverin", "Szörény"],
        9: ["Marcell", "Juliánusz"],
        10: ["Melánia", "Vilmos", "Vilma"],
        11: ["Ágota", "Honoráta"],
        12: ["Ernő", "Erneszta", "Tatjána"],
        13: ["Veronika", "Csongor", "Yvett"],
        14: ["Bódog", "Félix"],
        15: ["Lóránt", "Loránd", "Pál"],
        16: ["Gusztáv", "Marcell"],
        17: ["Antal", "Antónia"],
        18: ["Margit", "Piroska"],
        19: ["Sára", "Márta", "Márió"],
        20: ["Fábián", "Sebestyén"],
        21: ["Ágnes", "Agnéta"],
        22: ["Vince", "Artúr"],
        23: ["Zelma", "Rajmund", "Emerencia", "Emese", "Freja", "Frej"],
        24: ["Timót", "Ferenc"],
        25: ["Pál", "Henrik"],
        26: ["Vanda", "Paula", "Timóteusz"],
        27: ["Angéla", "Angelika"],
        28: ["Károly", "Karola", "Tamás"],
        29: ["Adél", "Valér"],
        30: ["Martina", "Gerda", "Jácinta"],
        31: ["Marcella", "János"],
    },
    2: {  # Február
        1: ["Ignác", "Brigitta", "Kincső", "Renátó"],
        2: ["Karolina", "Karola", "Aida"],
        3: ["Balázs", "Oszkár", "Celerina"],
        4: ["Ráhel", "Csenge", "Veronika", "András"],
        5: ["Ágota", "Ingrid", "Etelka", "Léda"],
        6: ["Dorottya", "Dóra", "Pál"],
        7: ["Tódor", "Rómeó", "Richárd"],
        8: ["Aranka", "Jeromos"],
        9: ["Abigél", "Alex", "Apollónia"],
        10: ["Elvira"],
        11: ["Bertold", "Marietta"],
        12: ["Lívia", "Lídia", "Eulália"],
        13: ["Ella", "Linda", "Levente", "Katalin"],
        14: ["Bálint", "Valentin", "Cirill", "Metód"],
        15: ["Kolos", "Györgyi", "Georgina"],
        16: ["Julianna", "Lilla", "Filippa"],
        17: ["Donát"],
        18: ["Bernadett", "Simon", "Zenkő"],
        19: ["Zsuzsanna", "Eliza", "Konrád"],
        20: ["Aladár", "Álmos", "Leó"],
        21: ["Eleonóra", "Zelmira", "Péter"],
        22: ["Gerzson", "Margit", "Zétény"],
        23: ["Alfréd", "Polikárp", "Mirtill"],
        24: ["Mátyás", "Jázmin"],
        25: ["Géza", "Cézár", "Vanda"],
        26: ["Viktor", "Győző", "Edina"],
        27: ["Ákos", "Bátor", "Gábor"],
        28: ["Elemér", "Oszvald", "Román"],
        29: ["— SZÖKŐÉV esetén ugyanaz, mint 28-án —"],
    },
    3: {  # Március
        1: ["Albin", "Albina", "Leonita"],
        2: ["Lujza", "Ágnes", "Henrik", "Magor"],
        3: ["Kornélia", "Kunigunda", "Frigyes"],
        4: ["Kázmér", "Lúciusz", "Zorán"],
        5: ["Adorján", "Adrián"],
        6: ["Leonóra", "Inez", "Koletta", "Felicitász"],
        7: ["Tamás", "Perpétua", "Ubul"],
        8: ["János", "Zoltán", "Apolka"],
        9: ["Franciska", "Fanni"],
        10: ["Ildikó", "Emil", "Gusztáv"],
        11: ["Szilárd", "Tímea", "Konstantin"],
        12: ["Gergely", "Maximilián"],
        13: ["Krisztián", "Ajtony", "Egyed", "Patrícia"],
        14: ["Matild", "Matilda", "Trilla"],
        15: ["Kristóf", "Kelemen"],
        16: ["Henrietta", "Herbert"],
        17: ["Gertrúd", "Patrik"],
        18: ["Sándor", "Ede", "Cirill"],
        19: ["József", "Bánk"],
        20: ["Klaudia", "Alexandra"],
        21: ["Benedek", "Bence", "Miklós"],
        22: ["Beáta", "Izolda", "Lea"],
        23: ["Emőke", "Botond", "Ottó", "Kartal"],
        24: ["Gábor", "Karina"],
        25: ["Irén", "Írisz", "Lúcia"],
        26: ["Emánuel", "Emánuéla", "Lara", "Larissza", "Árpád"],
        27: ["Hajnalka", "Lídia", "Auguszta"],
        28: ["Gedeon", "Johanna"],
        29: ["Auguszta", "Bercel", "Bertold"],
        30: ["Zalán"],
        31: ["Árpád", "Benjámin", "Benő"],
    },
    4: {  # Április
        1: ["Hugó", "Agád"],
        2: ["Áron", "Ferenc"],
        3: ["Buda", "Richárd", "Hóvirág", "Indira"],
        4: ["Izidor"],
        5: ["Vince", "Irén", "Teodóra"],
        6: ["Vilmos", "Bíborka", "Taksony", "Celesztin"],
        7: ["Herman", "János"],
        8: ["Dénes", "Valér", "Valter"],
        9: ["Erhard", "Ákos", "Döme"],
        10: ["Zsolt", "Ezékiel"],
        11: ["Leó", "Szaniszló", "Glória"],
        12: ["Gyula", "Baldvin", "Sába", "Nara"],
        13: ["Ida", "Márton", "Hermina"],
        14: ["Tibor"],
        15: ["Anasztázia", "Tas", "Oktávia"],
        16: ["Csongor", "Bernadett"],
        17: ["Rudolf", "Izidóra"],
        18: ["Andrea", "Ilma", "Apolló", "Aladár"],
        19: ["Emma", "Malvin", "Zseraldina"],
        20: ["Tivadar", "Tihamér", "Töhötöm"],
        21: ["Konrád", "Zelmira", "Anzelm"],
        22: ["Csilla", "Noémi", "Kájusz", "Noé"],
        23: ["Béla", "Adalbert"],
        24: ["György", "Fidél", "Debóra"],
        25: ["Márk", "Ányos", "Mohamed"],
        26: ["Ervin", "Klétusz"],
        27: ["Zita", "Mariann", "Anasztáz"],
        28: ["Valéria", "Péter"],
        29: ["Péter", "Katalin", "Roberta"],
        30: ["Katalin", "Kitti", "Zsófia", "Piusz"],
    },
    5: {  # Május
        1: ["Fülöp", "Jakab", "Zsaklin", "Jefte", "József", "Valburga", "Fédra"],
        2: ["Zsigmond", "Idir", "Zoé"],
        3: ["Tímea", "Irma", "Jakab", "Fülöp"],
        4: ["Mónika", "Flórián"],
        5: ["Györgyi", "Irén"],
        6: ["Ivett", "Frida", "Judit", "Yvett"],
        7: ["Gizella", "Gusztáv", "Bendegúz", "Gália"],
        8: ["Mihály", "Győző"],
        9: ["Gergely", "Katinka", "Alberta", "Édua", "Mira"],
        10: ["Ármin", "Pálma", "Izidor"],
        11: ["Ferenc", "Sára"],
        12: ["Pongrác"],
        13: ["Szervác", "Imola", "Imelda"],
        14: ["Bonifác", "Gyöngyi"],
        15: ["Bodza", "Zsófia", "Szonja", "Döníz"],
        16: ["Mózes", "Botond", "János"],
        17: ["Paszkál", "Ditmár", "Rezeda"],
        18: ["Erik", "Alexandra", "János", "Hanga"],
        19: ["Ivó", "Iván", "Milán"],
        20: ["Bernát", "Bernardin", "Felícia"],
        21: ["Konstantin", "András"],
        22: ["Júlia", "Rita", "Emil"],
        23: ["Dezső", "Vilmos", "Renáta"],
        24: ["Eszter", "Eliza", "Vanessza"],
        25: ["Orbán", "Gergely"],
        26: ["Fülöp", "Evelin"],
        27: ["Hella", "Pelbárt", "Ágoston"],
        28: ["Emil", "Csanád", "Vilmos"],
        29: ["Magdolna", "Magda", "Ervin", "Léna"],
        30: ["Janka", "Zsanett", "Johanna", "Nándor"],
        31: ["Angéla", "Petronella"],
    },
    6: {  # Június
        1: ["Tünde", "Jusztinusz"],
        2: ["Kármen", "Anita", "Péter", "Marcellinusz"],
        3: ["Klotild", "Cecília", "Károly", "Kevin"],
        4: ["Bulcsú", "Kerény", "Kerubin"],
        5: ["Frézia", "Zenke", "Fatime", "Fatima", "Bonifác"],
        6: ["Norbert", "Norberta", "Cintia"],
        7: ["Róbert", "Robertina", "Arianna", "Fülöp", "Roberta"],
        8: ["Medárd", "Helga"],
        9: ["Félix", "Előd", "Annamária", "Annabella"],
        10: ["Margit", "Gréta"],
        11: ["Barnabás", "Barangó"],
        12: ["Villő", "Orfeusz", "Adelaida", "Duru"],
        13: ["Antal", "Anett"],
        14: ["Vazul", "Elizeus", "Herta"],
        15: ["Jolán", "Vid", "Viola", "Ariana"],
        16: ["Jusztin", "Jusztina", "Auréliusz"],
        17: ["Laura", "Alida", "Alina", "Szabolcs", "Adolf", "Bató"],
        18: ["Arnold", "Levente", "Doloróza"],
        19: ["Gyárfás", "Romuald", "Azurea", "Zorka"],
        20: ["Rafael", "Dina"],
        21: ["Alajos", "Leila"],
        22: ["Paulina", "Tamás"],
        23: ["Zoltán", "Szultána"],
        24: ["János", "Iván"],
        25: ["Vilmos", "Viola", "Vilma"],
        26: ["János", "Pál", "Cirill"],
        27: ["László", "Sámson"],
        28: ["Levente", "Irén", "Iréneusz"],
        29: ["Péter", "Pál", "Adeliz", "Adeliza", "Emőke", "Judit", "Petra", "Szulamit", "Ivett"],
        30: ["Pál"],
    },
    7: {  # Július
        1: ["Tihamér", "Annamária", "Olivér", "Áron"],
        2: ["Ottó"],
        3: ["Kornél", "Soma", "Tamás"],
        4: ["Ulrik", "Erzsébet", "Fédra", "Babett"],
        5: ["Emese", "Sarolta", "Lotti", "Antal", "Nara"],
        6: ["Csaba", "Mária"],
        7: ["Apollónia", "Vilibald", "Bene"],
        8: ["Ellák", "Edgár", "Eperke", "Zsóka"],
        9: ["Lukrécia", "Veronika", "Hajnalka"],
        10: ["Amália", "Melina Engelbert", "Ulrika"],
        11: ["Nóra", "Lili", "Nelli", "Benedek"],
        12: ["Izabella", "Dalma", "Eleonóra"],
        13: ["Jenő", "Henrik"],
        14: ["Örs", "Stella", "Kamil"],
        15: ["Örkény", "Henrik", "Roland", "Bonaventúra", "Csegő"],
        16: ["Valter", "Irma"],
        17: ["Endre", "Elek", "András"],
        18: ["Szömér", "Frigyes", "Milla", "Hedvig", "Mirkó"],
        19: ["Emília"],
        20: ["Illés", "Margaréta"],
        21: ["Dániel", "Daniella", "Lőrinc"],
        22: ["Magdolna", "Mária", "Magda", "Nara"],
        23: ["Lenke", "Brigitta", "Apollinár"],
        24: ["Kinga", "Kunigunda", "Kincső", "Krisztina"],
        25: ["Kristóf", "Jakab"],
        26: ["Panna", "Anna", "Anikó", "Joakim"],
        27: ["Olga", "Liliána", "Natália", "Pantaleon"],
        28: ["Szabolcs", "Alina", "Ince", "Győző"],
        29: ["Márta", "Flóra"],
        30: ["Judit", "Xénia", "Péter"],
        31: ["Oszkár", "Ignác", "Bató"],
    },
    8: {  # Augusztus
        1: ["Boglárka", "Nimród", "Alfonz"],
        2: ["Lehel"],
        3: ["Hermina", "Lídia", "Kamélia", "Kíra", "Mirtill"],
        4: ["Domonkos", "Dominik", "János", "Dominika"],
        5: ["Krisztina"],
        6: ["Berta", "Bettina"],
        7: ["Ibolya"],
        8: ["László", "Domonkos"],
        9: ["Emőd", "Román"],
        10: ["Lőrinc", "Blanka", "Csilla"],        
        11: ["Zsuzsanna", "Töhötöm", "Klára"],
        12: ["Clarissa", "Klára", "Marcell"],
        13: ["Ipoly", "Hajnalka"],
        14: ["Marcell", "Alfréd"],
        15: ["Mária", "Napóleon"],
        16: ["Ábrahám", "Ábris"],
        17: ["Jácint", "Evelin", "Eszter"],
        18: ["Ilona", "Ilonka", "Jusztina"],
        19: ["Huba", "Huba", "Huba"],
        20: ["István", "István", "István"],
        21: ["Sámuel", "Hajna"],
        22: ["Menyhért", "Mirjam"],
        23: ["Bence", "Benedek"],
        24: ["Bertalan", "Ágoston"],
        25: ["Lajos", "Klaudia"],
        26: ["Izsó", "Izsó"],
        27: ["Gábor", "Gábor"],
        28: ["Ágoston", "Ágoston"],
        29: ["Beatrix", "Beatrix"],
        30: ["Rózsa", "Rózsa"],
        31: ["Kamilla", "Kamilla"],
    },
    9: { # Szeptember
        1: ["Egmont", "Körmendy", "Enikő"],
        2: ["Rebeka", "Bertalan"],
        3: ["Hilda", "Gréta"],
        4: ["Rozália", "Rozálie", "Rozina"],
        5: ["Viktor", "Viktória"],
        6: ["Zsófia", "Regina"],
        7: ["Regina", "Lőrinc"],
        8: ["Mária", "Nóra"],
        9: ["Ádám", "Éva"],
        10: ["Nóra", "Dénes"],
        11: ["Telekes", "Nándor"],
        12: ["Mária", "Fábián"],
        13: ["Kornél", "Ipoly"],
        14: ["Krisztián", "Roland"],
        15: ["Enikő", "Melitta"],
        16: ["Edit", "Hilária"],
        17: ["Zsófia", "Lőrinc"],
        18: ["Diána", "Edez"],
        19: ["Vilhelmina", "Vilma"],
        20: ["Friderika", "Frida"],
        21: ["Máté", "Máté"],
        22: ["Móric", "Tímea"],
        23: ["Tekla", "Bence"],
        24: ["Gellért", "Gellér"],
        25: ["Krisztián", "Eufrozina"],
        26: ["Iván", "Ivánka"],
        27: ["Hedvig", "Száva"],
        28: ["Vencel", "Vencel"],
        29: ["Mihály", "Gabriella"],
        30: ["Jeromos", "Róza"],
    },
    10: { # Október
        1: ["Malvin", "Remig"],
        2: ["Petra", "Aida"],
        3: ["Helga", "Kálmán"],
        4: ["Ferenc", "Franciska"],
        5: ["Aurél", "Tímea"],
        6: ["Brúnó", "Renáta"],
        7: ["Amália", "Ulrik"],
        8: ["Koppány", "Brigitta"],
        9: ["Dénes", "Szilárd"],
        10: ["Gedeon", "Gyöngyvér"],
        11: ["Brigita", "Nővérek"],
        12: ["Sára", "Dina"],
        13: ["Kálmán", "Ede"],
        14: ["Helén", "Lőrinc"],
        15: ["Teréz", "Terézia"],
        16: ["Gál", "Gálusz"],
        17: ["Hedvig", "Lukács"],
        18: ["Lukács", "Lukács"],
        19: ["Nándor", "Nándor"],
        20: ["Vendel", "Vendel"],
        21: ["Orsolya", "Orsolya"],
        22: ["Előd", "Előd"],
        23: ["Gyöngyi", "Gyöngyi"],
        24: ["Salamon", "Salamon"],
        25: ["Blanka", "Blanka"],
        26: ["Dömötör", "Dömötör"],
        27: ["Szabina", "Szabina"],
        28: ["Simon", "Simon"],
        29: ["Nárcisz", "Nárcisz"],
        30: ["Alfonz", "Alfonz"],
        31: ["Farkas", "Farkas"],
    },
    11: { # November
        1: ["Márton", "Felícia"],
        2: ["Achilles", "Levente"],
        3: ["Hubert", "Győző"],
        4: ["Károly", "Károly"],
        5: ["Imre", "Imre"],
        6: ["Lénárd", "Lénárd"],
        7: ["Rezeda", "Rezeda"],
        8: ["Zoltán", "Zoltán"],
        9: ["Tivadar", "Tivadar"],
        10: ["Réka", "Réka"],
        11: ["Árpád", "Árpád"],
        12: ["József", "József"],
        13: ["Szilvia", "Szilvia"],
        14: ["Aliz", "Aliz"],
        15: ["Albert", "Albert"],
        16: ["Ödön", "Ödön"],
        17: ["Gertrúd", "Gertrúd"],
        18: ["Román", "Román"],
        19: ["Erzsébet", "Erzsébet"],
        20: ["Jolán", "Jolán"],
        21: ["Olivér", "Olivér"],
        22: ["Cecília", "Cecília"],
        23: ["Kelemen", "Kelemen"],
        24: ["Emília", "Emília"],
        25: ["Katalin", "Katalin"],
        26: ["Virág", "Virág"],
        27: ["Virgil", "Virgil"],
        28: ["Károly", "Károly"],
        29: ["Taksony", "Taksony"],
        30: ["András", "András"],
    },
    12: { # December
        1: ["Elza", "Natália"],
        2: ["Melinda", "Vivien"],
        3: ["Ferenc", "Kornél"],
        4: ["Barbára", "Boróka"],
        5: ["Vilma", "Sára"],
        6: ["Miklós", "Nárcisz"],
        7: ["Ambrus", "Amasis"],
        8: ["Mária", "Luca", "Melinda"],
        9: ["Natália", "Natán"],
        10: ["Judit", "Luca"],
        11: ["Árpád", "Árpád"],
        12: ["Szilárd", "Melinda"],
        13: ["Luca", "Kornél"],
        14: ["Ivett", "Szilveszter"],
        15: ["Valér", "Valéria"],
        16: ["Etelka", "Aletta"],
        17: ["Lázár", "Olympia"],
        18: ["Auguszta", "Auguszta"],
        19: ["Viola", "Natália"],
        20: ["Teofil", "Tivadar"],
        21: ["Tamás", "Tímea"],
        22: ["Zénó", "Flóra"],
        23: ["Viktória", "Eliza"],
        24: ["Ádám", "Éva"],
        25: ["Karácsony"],
        26: ["István", "Jenő"],
        27: ["János", "Virág"],
        28: ["Kamilla", "Károly"],
        29: ["Tamás", "Dávid"],
        30: ["Dávid", "Olga"],
        31: ["Szilveszter", "Szilvi"],
        },
        }